service: resize

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  timeout: 40
  profile: upframe
  region: eu-west-2

functions:
  resize:
    handler: src/handler.resize
    environment:
      stage: ${self:provider.stage}
    events:
      - s3:
          bucket: upframe-test-image-resize
          event: s3:ObjectCreated:*
          existing: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  bucket:
  serverless-offline:
    port: 9000
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
