service: resize

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  timeout: 40
  profile: upframe
  region: eu-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: arn:aws:s3:::${self:custom.bucket.name}/*

functions:
  resize:
    handler: src/handler.resize
    environment:
      stage: ${self:provider.stage}
      BUCKET_NAME: ${self:custom.bucket.name}
    events:
      - s3:
          bucket: ${self:custom.bucket.name}
          event: s3:ObjectCreated:*
          existing: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 9000
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
  bucket:
    name: upframe-test-image-resize
