service: resize

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  timeout: 40
  region: eu-west-2

functions:
  resize:
    handler: src/handler.resize
    environment:
      stage: ${self:provider.stage}
      BUCKET_NAME: ${env:BUCKET_NAME}
      BUCKET_REGION: ${env:BUCKET_REGION}
      AWS_KEY_ID: ${ssm:/resize/AwsKeyId}
      AWS_KEY_SECRET: ${ssm:/resize/AwsKeySecret~true}
      DEV_DB_HOST: ${ssm:/DB/Dev/Host}
      DEV_DB_NAME: ${ssm:/DB/Dev/Name}
      DEV_DB_USER: ${ssm:/DB/Dev/User}
      DEV_DB_PASS: ${ssm:/DB/Dev/Password~true}
      PROD_DB_HOST: ${ssm:/DB/Prod/Host}
      PROD_DB_NAME: ${ssm:/DB/Prod/Name}
      PROD_DB_USER: ${ssm:/DB/Prod/User}
      PROD_DB_PASS: ${ssm:/DB/Prod/Password~true}

    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true
      - http:
          method: POST
          path: /resize

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 9000
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
